### ISSUE TITLE
Question: Blocklist

### ISSUE THREAD

**Issue by gamebird92** [pylorak/TinyWall#11]
Hello,
i did a look into Tinywall and saw the feature "enable blocklist"...
In settings I can find port-based and domain-based blocklist. 

Recommended is domain-based blocklist... But here comes my question: Which blocklists are included???
Is there a way to view them?

Best regards,

**Comment by dramumard** [comment]
The port-based blocklist is a custom one compiled by myself. This one is not recommended anymore because in today's internet port blocking offers little security, and at the same time it often causes connection issues for legitimate applications. You can find its contents in the source repo in TinyWall/Database/PortBlocklist.json.

The domain-based blocklist is the MVPS hosts file. This used to be a superb blocklist but the author has stopped updating it. Still it functions great even today. [Link to contents](https://winhelp2002.mvps.org/hosts.htm)

Personal rant (for anybody who wishes to work on these features):
In a future version of TinyWall, IMHO port-based blocklist feature should be removed completely, and the domain-based blocklist should be extended to support custom lists. For the standard blocklist, it'd be best to start looking for an alternative for the MVPS hosts file.

**Comment by pylorak** [comment]
he port-based blocklist is a custom one compiled by myself. This one is not recommended anymore because in today's internet port blocking offers little security, and at the same time it often causes connection issues for legitimate applications. You can find its contents in the source repo in TinyWall/Database/PortBlocklist.json.

The domain-based blocklist is the MVPS hosts file. This used to be a superb blocklist but the author has stopped updating it. Still it functions great even today. [Link to contents](https://winhelp2002.mvps.org/hosts.htm)

Personal rant (for anybody who wishes to work on these features):
In a future version of TinyWall, IMHO port-based blocklist feature should be removed completely, and the domain-based blocklist should be extended to support custom lists. For the standard blocklist, it'd be best to start looking for an alternative for the MVPS hosts file.
