### ISSUE TITLE
Connections window shows IPv6 addresses backwards

### ISSUE THREAD

**Issue by saukkko** [pylorak/TinyWall#13]
Hi, there's an issue how the connections window display the IPv6 addresses. They're all half-backwards and when combined with leading zero truncation, they can also look very confusing.

For example, with link-local address of `fe80::e9df:7c76:13d1:3114` TinyWall displays `1431:d113:767c:dfe9::80fe`.

!["Link-local IPv6 Address"](https://cdn.discordapp.com/attachments/970723785835700244/1112140030094352394/image.png)

<br>

Same thing happens with remote addresses. For example, Google Public DNS Server IPv6 addresses are `2001:4860:4860::8888` and `2001:4860:4860::8844`, but we see `8888::6048:6048:120` instead

!["Google Public DNS"](https://cdn.discordapp.com/attachments/970723785835700244/1112140062017191976/image.png)

Not a deal breaker or anything but somewhat annoying and renders the "Copy remote address" function useless.

**Comment by pylorak** [comment]
It seems only the "Blocked" entries in the connections window are affected, not the others. That is probably why I haven't noticed it. Just to be sure, could you verify and confirm that other entries are OK? They seem to be on my computer.

**Comment by 1xdevnet** [comment]
I can confirm that the behavior on my PC is as you described - active connections are displayed correctly, but blocked connections are reversed pairs, for both the local and remote address columns.
As another example MpDefenderCoreService.exe shows a blocked connection as `3201::4200:ec01:2026`, rather than `2620:01ec:0042::0132`.
Meanwhile Firefox.exe has an allowed connection to GitHub and correctly shows it as `2606:50c0:8000::154`.

**Comment by pylorak** [comment]
Thanks, I have a fix prepared. I'll push it shortly to the repo with some other stuff as well.
