### ISSUE TITLE
Tinywall mode on normal protection after pc restart

### ISSUE THREAD

**Issue by maxservice** [pylorak/TinyWall#15]
Tinywall mode is on normal protection after pc restart. If i set disabled mode it will  change after restart. Can we  fix it? Thank you very much.

**Comment by Valutin** [comment]
On my side, it is randomy going back to normal protection after a restart. I actually rarely use tinywall, I use it when I am using my smartphone hotspot to save on data, I found tinywall very quick and easy to configure what software has access to the connection so it stays most of the time in "disable" mode. But on some days, on some restart, it will turn back into normal mode by itself. I can't switch it back to disable, the GUI is not accessible and I can't turn off tiniwall service. It's messing with my computer soo badly that I have to restart windows. Not sure why it is acting this way.

**Comment by navhaxs** [comment]
I saw there is this config item here https://github.com/pylorak/TinyWall/blob/cc4bad41341e6ddd24a26aef0eb85d88c8862d98/TinyWall/ServerConfiguration.cs#L158 but no UI to configure it.

I guess some of us would prefer setting this to `FirewallMode.Disabled` so that we can enable TinyWall on demand, rather than always on boot up? :)

**Comment by maxservice** [comment]
won't work, if you roll over with the mouse on the tray icon said unknown mode and the icon change to white shield.

**Comment by pylorak** [comment]
This is actually intended. If firewall mode is set to Disabled or Learning mode, it will spring back to the previously saved mode after a restart. This is so that users cannot forget to re-enable the firewall indefinitely (learning mode basically means firewall is disabled). For example, if the mode is Allow Outgoing, it will keep that and not change the mode upon a reboot.

**Comment by bitkris-dev** [comment]
> This is actually intended. If firewall mode is set to Disabled or Learning mode, it will spring back to the previously saved mode after a restart. This is so that users cannot forget to re-enable the firewall indefinitely (learning mode basically means firewall is disabled). For example, if the mode is Allow Outgoing, it will keep that and not change the mode upon a reboot.

this is inaccurate, it's happening currently to me, at the end of 2025. "Allow outgoing" but when I restart my computer it goes back to Normal. Is there any way to prevent this?
