### ISSUE TITLE
TinyWall caused BSOD 3 times.

### ISSUE THREAD

**Issue by Rexadev** [pylorak/TinyWall#20]

**Comment by tnodir** [comment]
@Rexadev Can you please provide screenshot of BSOD?

**Comment by pylorak** [comment]
TinyWall literally cannot cause a BSOD, as it never installs any kernel code. If you get BSODs while TinyWall is running then it must be a fault in the kernel driver/component of another application. Maybe it doesn't handle being blocked and crashes instead. Assuming it crashes due to the blocking then you might get around it by whitelisting "System" in TinyWall.
