### ISSUE TITLE
Copyright Year in 'About'

### ISSUE THREAD

**Issue by Barough** [pylorak/TinyWall#25]
The copyright year in 'About' should be adressed. It say 2011.

**Comment by 9ao9ai9ar** [comment]
Discussion: https://news.ycombinator.com/item?id=34880663.

Maybe the copyright year can be dropped altogether. Likewise for "[All rights reserved](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence)".

**Comment by pylorak** [comment]
The way it is right now is correct, changing it would be false.

The year in a copyright notice is the **first** year to claim copyright. Since TinyWall was first released publicly in 2011, that's the correct year to name. The copyright year only needs an update when it is given as a span, so for example if it said 2011-2023, then in 2024 it would need to be updated to 20111-2024.
