### ISSUE TITLE
Removing pop ups is actually a lack not a feature.

### ISSUE THREAD

**Issue by Shituation** [pylorak/TinyWall#3]
The app boasts about not showing pop ups for blocked apps... I wonder how can you really have control over a firewall that doesn't let you know what apps are doing until you manually check it.

Its not a feature, its a lack.

**Comment by eurobank** [comment]
You watch the Connections blocked and unblock what you need to allow.

**Comment by Shituation** [comment]
I expect a firewall to send me a pop up asking me to to allow or reject a connection. This is not a feature.

**Comment by pylorak** [comment]
This has been extensively explained on the website. For your reference:

>  Most firewalls are based on the same interaction principles. Basically, whenever an application is trying to access the internet, display a popup asking the user what to do. This is not only annoying for the user, but is also less than secure. On an average computer, a lot of applications are trying to access the internet. Displaying a popup for each app makes it very probable that unneeded applications will gain access to the network, as it increases the likelyhood of the user granting unnecessary rights to many applications. This phenomenon could be characterized as "security fatigue", and at its extreme, the user does not verify any more what he gives internet access, but just blindly allows programs that ask for it.
> 
> TinyWall takes a different approach. It does not display popups that urge users to whitelist apps. In fact, it will not notify you of any blocked action at all in real-time. Instead of showing popups, TinyWall makes it easy to whitelist or unblock applications by different means. For example, you can just initiate whitelisting by a hotkey, then click on a window that you want to allow. Or, you can select an application from the list of running processes. Of course, the traditional way of selecting an executable also works. This approach avoids popups, but still keeps the firewall very easy to use. Most importantly, with the no-popup approach, the user will only notice that a program has been denied internet access when he can't use it any more. Consequently, users will only unblock applications that they actually need and none more, which is optimal from a security standpoint. 

A couple of additional notes:
- As noted by eurobank, you can still check in TinyWall what is using your network, so you're not losing that information.
- If the user were given the option to turn popups on and off, many would just turn it on because that's what they were taught by other firewalls, no matter how bad that practice is.
- Yes this a feature, not just a lack thereof. Because it not only increases security, but a part of this are multiple other actual features that make whitelisting easier without popups.

**Comment by Shituation** [comment]
Ok, keep trying with "its a feature ". The user is always stupid, you the developers are geniuses. That is why you make a firewall that doesn't warn the user if its blocking an app or not. 

Good bye.

**Comment by pylorak** [comment]
There's no need to act so cynical just because I don't believe the way you want to use a firewall doesn't align with TinyWall's principles. You claim you know better because you're the user? You're forgetting that I am also a user of TinyWall. TinyWall came to life because I want to **use** a software like this. Some users (like me) like how TinyWall works, some others (like you) don't. Neither of us are alone. It is normal to have multiple software for a single task, all with different working principles and UIs, and all cater for different users. If you don't believe TinyWall is suited for you, that's alright, I don't think you're stupid, we just have different expectations.
