### ISSUE TITLE
Add PID (process id) in connections list

### ISSUE THREAD

**Issue by Windree** [pylorak/TinyWall#38]
Hello.
It would be nice to see a process id in connections.
For example:
In the list I can see svchost.exe or taskhostw.exe but can't understand what service or what task has been blocked. PID will be very helpful to determinate what service or a task where blocked

![image](https://github.com/pylorak/TinyWall/assets/57554809/9c9c2495-125b-41ed-b4fe-55399975be9d)

**Comment by 9ao9ai9ar** [comment]
The PIDs are already shown in the connections list: if you look at the heading of the first column, you'll see that the PIDs are the numbers enclosed in parentheses after the process names. The `taskhostw.exe` you have highlighted probably doesn't have a PID because it has already exited, as you're showing blocked apps in the last 5 minutes.

**Comment by pylorak** [comment]
Ports are only not shown for blocked processes, and the reason is Windows does not provide that information.
