### ISSUE TITLE
Application exceptions list is cleared on forced shutdown

### ISSUE THREAD

**Issue by 9ao9ai9ar** [pylorak/TinyWall#39]
The latest version 3.3.1 is still affected by this bug. Had to reimport the list from backup after a power cut or forced shutdown.

**Comment by pylorak** [comment]
I suspect your filesystem and/or harddrive could have other problems. Whenever TinyWall needs to save its config, it first writes it to a temporary file in the same directory of the real config file, and then it does a file move to replace the final file. **A file move on any modern file system is an atomic operation** (even NTFS), meaning after the move you either have the full contents of the old file or the full contents of the new file, never something in-between (not even on a power failure or forced shutdown). This means you might lose changes made since the last save, but the file itself should never get lost, half-written, or corrupted.

If you have file corruptions to TinyWall's config, then something is wrong on your computer. There is however something I can do for you. TinyWall 3.3 always does a config save when shutting down. This is not always needed. I'll change TinyWall to only save the config when there is a change, which should reduce the chance of corruptions for people with bad hardware or some other problem.

**Comment by 9ao9ai9ar** [comment]
I report back to confirm my issue is fixed with the first released test build for v3.4, as I just experienced another power cut a few weeks ago.

**Comment by 9ao9ai9ar** [comment]
By the way, why is it showing me as the committer on this page (and some other issue pages in this repo)?
