### ISSUE TITLE
Playing a game online

### ISSUE THREAD

**Issue by vaiium** [pylorak/TinyWall#48]
I play rocket league on and off. The last time i did, i didn't have tinywall installed.

Now everytime i start it, it wont connect to the rocket league servers. Even if I give rocketleague.exe full acces. Even when i turn all firewall protection off. It will only connect when i have tinywall uninstalled.

**Comment by CygnusBl4ck** [comment]
Did you whitelist Epic Launcher?
C:\Program Files (x86)\Epic Games\Launcher\Engine\Binaries\Win64
C:\Program Files (x86)\Epic Games\Launcher\Engine\Binaries\Win32
C:\Program Files\Epic Games\rocketleague

**Comment by vaiium** [comment]
Yes! I got it to work, but only through auto learn mode. Wich kinda beats the purpose, because than i have to unwhitelist a bunch of processes again. But i cant seem to find the one responsible for rocket league. 

Its a fault on my end. I just cant seem to find it.

**Comment by pylorak** [comment]
If you have any game/Epic-related rules whitelisting services, you could try whitelisting them as executable instead. This helps sometimes with other apps, because they can get picked up as services when you whitelist them from the Connections window, but they still make internet connections outside of their service process, so you actually need to whitelist them as simple executables. Not sure if this will help, but worth a try.
